Pepper/Pepper/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('pepper_app/', include('pepper_app.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Pepper/PepperFiles/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('pepper/', include('pepper.urls')),
    path('admin/', admin.site.urls),
]

Pepper/pepper_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.ItemsListView.as_view(), name='items-list'),
    path('category/<slug:slugged_category>/', views.ItemsListView.as_view(), name='category-filtered-items-list'),
    path('subcategory/<slug:slugged_subcategory>/', views.ItemsListView.as_view(), name='subcategory-filtered-items'
                                                                                        '-list'),
    path('<int:id>/<slug:slugged_title>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('create/', views.ItemCreateView.as_view(), name='item-create'),
    path('categories/', views.ItemsListView.as_view(), name='categories'),
    path('search/', views.SearchResultsView.as_view(), name='search'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
]

Pepper/pepper_app/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.template.defaultfilters import slugify
# ----------------------Models----------------------------------------------


class Category(models.Model):
    """
    Model of a category of items,
    contains also subcategories
    """
    name = models.CharField(max_length=50)
    slugged_category = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created objects, so set slug
            self.name = self.name.title()
            self.slugged_category = slugify(self.name)

            super(Category, self).save(*args, **kwargs)


class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    slugged_subcategory = models.SlugField(blank=True, null=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created objects, so set slug
            self.slugged_subcategory = slugify(self.name)

            super(Subcategory, self).save(*args, **kwargs)


class Item(models.Model):
    """
    Model of an item with reduced price.
    """
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=100)
    slugged_title = models.SlugField(blank=True)
    url = models.URLField(blank=True)
    description = models.TextField(blank=True)
    original_price = models.FloatField(blank=True, null=True)
    retail_price = models.FloatField(blank=True, null=True)
    currency = models.CharField(max_length=10, blank=True, null=True)
    still_up_to_date = models.BooleanField(default=True)
    pub_date = models.DateTimeField(default=timezone.now)
    img = models.ImageField(upload_to='pictures/', default='pictures/default/default.png')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created objects, so set slug
            self.slugged_title = slugify(self.title)

            super(Item, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-pub_date']
# ----------------------Models----------------------------------------------

Pepper/pepper_app/forms.py
from django import forms

from .models import Item, Subcategory, Category

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from bootstrap_modal_forms.mixins import PopRequestMixin, CreateUpdateAjaxMixin


class CustomUserCreationForm(PopRequestMixin, CreateUpdateAjaxMixin,
                             UserCreationForm):
    class Meta:
        model = User
        fields = ['username',
                  'password1',
                  'password2']


class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username',
                  'password']


class ItemModelForm(forms.ModelForm):
    title = forms.CharField(label='',
                            widget=forms.Textarea(
                                attrs={
                                    "placeholder": "Title of the steal",
                                    "rows": 1,
                                    "cols": 50,
                                }))
    description = forms.CharField(label='', widget=forms.Textarea(attrs={"placeholder": "Few words about it"}))

    class Meta:
        model = Item
        fields = (
            'category',
            'subcategory',
            'title',
            'description',
            'url',
            'pub_date',
            'original_price',
            'retail_price',
            'currency',
            'still_up_to_date',
            'img')
        exclude = (
            'slugged_title',
            'pub_date',
            'still_up_to_date')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['subcategory'].queryset = Subcategory.objects.none()

        if 'category' in self.data:
            try:
                category_id = int(self.data.get('category'))
                self.fields['subcategory'].queryset = \
                    Subcategory.objects.filter(category_id=category_id).order_by('name')
            except(ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['subcategory'].queryset = self.instance.category.subcategory_set.order_by('name')

    def clean(self):
        cleaned_data = super(ItemModelForm, self).clean()
        retail_price_field = cleaned_data.get("retail_price")
        original_price_field = cleaned_data.get("original_price")
        currency_field = cleaned_data.get("currency")

        if not retail_price_field and (currency_field or original_price_field):
            raise forms.ValidationError('Please fill retail price field.')
        elif retail_price_field and not currency_field:
            raise forms.ValidationError('Please fill currency field.')

        return cleaned_data

Pepper/pepper_app/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.contrib.auth.models import User

from .models import Category, Item, Subcategory
from .forms import ItemModelForm

from django.contrib.messages.views import SuccessMessageMixin
from bootstrap_modal_forms.mixins import PassRequestMixin
from bootstrap_modal_forms.generic import BSModalLoginView
from .forms import CustomUserCreationForm, CustomAuthenticationForm

# ------------------------------------------------------------------


class ItemsListView(ListView):
    """
    View with 10 latest steals,
    Choice of category,
    Nav bar with groups
    """

    template_name = 'pepper_app/items_list.html'
    context_object_name = 'items'

    def get_queryset(self):
        _category_slug = self.kwargs.get("slugged_category")
        _subcategory_slug = self.kwargs.get("slugged_subcategory")

        # Checking if user filtered items by category or subcategory.
        if _subcategory_slug:
            # Getting queryset of items that belong to the subcategory.
            subcategory = Subcategory.objects.get(slugged_subcategory=_subcategory_slug)
            return Item.objects.filter(subcategory=subcategory).order_by("-pub_date")
        elif _category_slug:
            # Getting queryset of items that belong to the category.
            category = Category.objects.get(slugged_category=_category_slug)
            return Item.objects.filter(category=category).order_by('-pub_date')
        else:
            # User hasn't chosen any filter so every item is being displayed.
            return Item.objects.order_by('-pub_date')


class SearchResultsView(ListView):
    template_name = 'pepper_app/items_list.html'
    context_object_name = 'items'
    model = Item

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Item.objects.filter(Q(title__icontains=query) |
                                          Q(description__icontains=query) |
                                          Q(category__name__icontains=query) |
                                          Q(subcategory__name__icontains=query)).order_by('-pub_date')
        return object_list


class ItemDetailView(DetailView):
    """
    View with details of steal,
    Can be up/down voted, deleted
    """
    model = Item
    template_name = 'pepper_app/item_details.html'
    context_object_name = 'item'

    def get_object(self):
        slug_ = self.kwargs.get("slugged_title")
        return get_object_or_404(Item, slugged_title=slug_)


class ItemCreateView(CreateView):
    """
    View to create an item
    """
    template_name = 'pepper_app/create_item.html'
    form_class = ItemModelForm
    success_url = reverse_lazy('items-list')

    def get_success_url(self):
        return self.success_url


class SignUpView(PassRequestMixin, SuccessMessageMixin, CreateView):
    form_class = CustomUserCreationForm
    template_name = 'pepper_app/signup.html'
    success_message = 'Success: Sign up succeeded. You can now log in.'
    success_url = reverse_lazy('items-list')


class CustomLoginView(BSModalLoginView):
    authentication_form = CustomAuthenticationForm
    template_name = "pepper_app/login.html"
    success_message = "Success: You were successfully logged in."
    extra_context = dict(success_url=reverse_lazy('items-list'))


def load_subcategories(request):
    """
    Function used in dropdown chained list while creating new item.
    :param request:
    :return: Subcategories of chosen category
    """
    category_id = request.GET.get('category')
    subcategories = Subcategory.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'pepper_app/dropdown_list.html', {'subcategories': subcategories})

Pepper/pepper_app/templates/pepper_app/create_item.html
{% extends 'base.html' %}

{% block content %}

  <h2>What's the steal?</h2>

  <form method="post" id="createItem" enctype="multipart/form-data" data-subcategories-url="{% url 'ajax_load_subcategories' %}" novalidate>
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button class="btn btn-light" type="submit">Save</button>
  </form>

  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_category").change(function () {
      var url = $("#createItem").attr("data-subcategories-url");
      console.log(url);
      var categoryId = $(this).val();

      $.ajax({
        url: url,
        data: {
          'category': categoryId
        },
        success: function (data) {
          console.log(data);
          console.log($("#id_subcategory").html(data));
          $("#id_subcategory").html(data)
        }
      });

    });
  </script>

{% endblock %}

Pepper/pepper_app/templates/pepper_app/dropdown_list.html
<option value="">----------</option>
{% for subcategory in subcategories %}

<option value="{{ subcategory.pk }}">{{ subcategory.name }}</option>
{% endfor %}

Pepper/pepper_app/templates/pepper_app/item_details.html
{% extends 'base.html' %}


{% block content %}
    <h1>{{ item.title }}</h1>
    <p>{{ item.description }}</p>
    <p>{{ item.original_price }}</p>
    <p>{{ item.retail_price }}</p>
    {% if item.url %}
        <a href="{{ item.url }}">Link</a>
    {% endif %}
{% endblock %}

Pepper/pepper_app/templates/pepper_app/items_list.html
{% extends 'base.html' %}
{% load static %}
{% load percentage %}
{% block content %}



    <div class=container" style="width: 70%; margin-left: 6%; padding-top: 30px;">
        <div class="row">
            {% for item in items %}
                   <div class="col-md-4 col-sm-12 col-lg-3">
                       <div class="card my-1 text-white bg-dark" style="max-width: 270px; min-height: 375px;">
                           <div class="img-frame" style="height: 200px;">
                           <div class="frame" style="display: flex; height: 200px; width: 100%; position: relative;
                             justify-content: center; align-items: center;">
                           {% if item.img %}
                             <img class="card-img-top" src="{{ item.img.url }}" style="padding-top: 35px;
                                                                                max-width: 100%;width: auto;
                                                                                height: auto; max-height:100%;">
                           {% endif %}
                           </div>
                           </div>
                           <div class="card-body">
                                <h5 class="card-title text-truncate">{{ item.title }}</h5>
                                {% if item.retail_price %}
                                    <div class="row">
                                        <span class="content pl-3" style="color: DarkOrange; font-weight: bold;
                                        font-size: 16px; max-width: 100%; text-align: center;"
                                                 >{{ item.retail_price }}{{ item.currency }}</span>
                                        {% if item.original_price %}
                                            <del class="original-price pl-3" style="color: darkgray; font-size: 14px;
                                             max-width: 100%; text-align: left;"
                                                    >{{ item.original_price }}{{ item.currency }}</del>
                                            <span class="discount pl-3" style="color: DarkOrange;
                                             font-size: 16px; text-align: center; max-width: 100%">
                                                {% discount item.original_price item.retail_price %}</span>
                                        {% endif %}
                                    </div>
                                {% endif %}
                           </div>
                           <div class="card-footer text-center">
                               <a href="{% url 'item-detail' item.id item.slugged_title %}" class="btn"
                                  style="width: 100%; background-color: DarkOrange;">Details</a>
                           </div>
                       </div>
                   </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

Pepper/pepper_app/templates/pepper_app/login.html
{% load widget_tweaks %}

<form method="post" action="">
    {% csrf_token %}

        <div class="modal-header">
            <h3 type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </h3>
        </div>

        <div class="modal-body">

            <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                {% for error in form.non_field_errors %}
                    {{ error }}
                {% endfor %}
            </div>

            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {% render_field field class="form-control" placeholder=field.label %}
                    <div class="{% if field.errors %} invalid{% endif %}">
                        {% for error in field.errors %}
                            <p class="help-block">{{ errors }}</p>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
            <input type="hidden" name="next" value="{{ success_url }}">
        </div>
    <div class="modal-footer">
        <button type="button" class="submit-btn btn"
                style="background-color: darkorange; color: dark;">Log in</button>
    </div>
</form>

Pepper/pepper_app/templates/pepper_app/signup.html
{% load widget_tweaks %}

<form method="post" action="">
  {% csrf_token %}

  <div class="modal-header">
    <h3 class="modal-title">Sign up</h3>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>

  <div class="modal-body">

    <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>

    {% for field in form %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
        {% render_field field class="form-control" placeholder=field.label %}
        <div class="{% if field.errors %} invalid{% endif %}">
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      </div>
    {% endfor %}
  </div>

  <div class="modal-footer">
    <button type="button" class="submit-btn btn btn-primary">Sign up</button>
  </div>

</form>